services:
  postgres:
    image: postgres:16.6-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/init-keycloak.sql:/docker-entrypoint-initdb.d/init-keycloak.sql
    ports:
      - 5432:5432

  keycloak:
    build:
      context: .
      dockerfile: Dockerfile
    image: bitnami-keycloak-mod:26.0.0-user-query-spi
    environment:
      KC_DB_USERNAME: 'keycloak'
      KC_DB_PASSWORD: 'password'
      KEYCLOAK_DATABASE_HOST: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KEYCLOAK_HTTP_RELATIVE_PATH: auth
    ports:
      - 8282:8080
      - 6006:8787
    depends_on:
      - postgres
